name: live_streaming
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0+2
  path_provider: ^2.0.11
  http: ^0.13.6
  uuid: ^3.0.7
  flutter_webrtc: ^0.9.26
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
